// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RisingWaveDotnetMaterializedView.DbHelpers;

#nullable disable

namespace RisingWaveDotnetMaterializedView.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230605122952_CreateAverageSpeedMaterializedView")]
    partial class CreateAverageSpeedMaterializedView
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AverageSpeedView", b =>
                {
                    b.Property<decimal>("AvgSpeed")
                        .HasColumnType("numeric");

                    b.Property<long>("NoOfTrips")
                        .HasColumnType("bigint");

                    b.Property<decimal>("TotalDistance")
                        .HasColumnType("numeric");

                    b.Property<TimeSpan>("TotalDuration")
                        .HasColumnType("interval");

                    b.ToTable((string)null);

                    b.ToView("mv_avg_speed", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
